# Pytorch zero to gan : First Assignment

### PyTorch is an open source machine learning library based on the Torch library, used for applications such as computer vision and natural language processing, primarily developed by Facebook's AI Research lab.

# The choosen functions are as follows:- 
- torch.zeros()
- torch.arange()
- torch.linspace()
- torch.eye()
- torch.cat()

In [0]:
# Import torch and other required modules
import torch

## Function 1 - torch.zeros()
Returns a tensor filled with the scalar value 0, with the shape defined by the variable argument size.

In [3]:
# Example 1 
torch.zeros(10,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

Create a matrix of 10 rows and 3 columns , filled with zeros 

In [8]:
# Example 2
torch.zeros(10 , requires_grad=True)

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], requires_grad=True)

Ten rows of zeros with requires_grad set to True

In [13]:
# Example 3 - breaking
torch.zeros(02)

SyntaxError: ignored

We should not use 02 when passing the int to the zeros, 02 is not as same as 2. 

- We should use this function when we need a matrix with zeros , or we want to do some linear work from scratch

## Function 2 - torch.arange()

Returns a 1-D tensor of size end-start/step with values from the interval [start, end) taken with common difference step beginning from start.

In [15]:
# Example 1
torch.arange(start=0,end=10,step=3)

tensor([0, 3, 6, 9])

We create a tensor using arange function where we give start to be 0 and end to be 10 wit step 3 . So the first value will be zero and later i+3,

In [16]:
# Example 2
torch.arange(1,1.5,0.2)

tensor([1.0000, 1.2000, 1.4000])

We can also give it a float value and in return we get a list of tensors .

In [18]:
# Example 3 - breaking 
torch.arange([1,2,3])

TypeError: ignored

We cannot pass list when creating a tensor using arange , it only accepts start , end and step

- Use this function when you need a specific tensors values

## Function 3 - torch.linspace()

Returns a one-dimensional tensor of steps equally spaced points between start and end.

The output tensor is 1-D of size steps.

In [19]:
# Example 1 - working

torch.linspace(10,1)

tensor([10.0000,  9.9091,  9.8182,  9.7273,  9.6364,  9.5455,  9.4545,  9.3636,
         9.2727,  9.1818,  9.0909,  9.0000,  8.9091,  8.8182,  8.7273,  8.6364,
         8.5455,  8.4545,  8.3636,  8.2727,  8.1818,  8.0909,  8.0000,  7.9091,
         7.8182,  7.7273,  7.6364,  7.5455,  7.4545,  7.3636,  7.2727,  7.1818,
         7.0909,  7.0000,  6.9091,  6.8182,  6.7273,  6.6364,  6.5455,  6.4545,
         6.3636,  6.2727,  6.1818,  6.0909,  6.0000,  5.9091,  5.8182,  5.7273,
         5.6364,  5.5455,  5.4545,  5.3636,  5.2727,  5.1818,  5.0909,  5.0000,
         4.9091,  4.8182,  4.7273,  4.6364,  4.5455,  4.4545,  4.3636,  4.2727,
         4.1818,  4.0909,  4.0000,  3.9091,  3.8182,  3.7273,  3.6364,  3.5455,
         3.4545,  3.3636,  3.2727,  3.1818,  3.0909,  3.0000,  2.9091,  2.8182,
         2.7273,  2.6364,  2.5455,  2.4545,  2.3636,  2.2727,  2.1818,  2.0909,
         2.0000,  1.9091,  1.8182,  1.7273,  1.6364,  1.5455,  1.4545,  1.3636,
         1.2727,  1.1818,  1.0909,  1.00

Create a random date start with 10 and end in 1

In [20]:
# Example 2 - working
torch.linspace(1,10,5)

tensor([ 1.0000,  3.2500,  5.5000,  7.7500, 10.0000])

From 1 to 10 get a 5 equally distributed datas.

In [24]:
# Example 3 - breaking
torch.linspace(10)

TypeError: ignored

We should pass ending argument to the linspace because the function needs to know when it should end

- We should use this function to get random data points with start and end as default params

## Function 4 - torch.eye()

Return identity matrix ( Identity matrix is something which we need when we are finding the inverse of the matrix)

In [25]:
# Example 1 - working
torch.eye(2)

tensor([[1., 0.],
        [0., 1.]])

Return a 2D identity matrix

In [40]:
# Example 2 - working
torch.eye(n=3,m=4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]])

Create a 2d identity matrix with 3 rows and 4 columms

In [38]:
# Example 3 - breaking
torch.eye(n=3,m=5 , dtype='float')

TypeError: ignored

We should provide torch.float to get a float values rather using float as string

- Use this function when we need to create an identity matrix to find an inverse of an matrix

## Function 5 - torch.cat()

Concatenates the given sequence of seq tensors in the given dimension.
0-row
1-column

In [58]:
# Example 1 - working
x = torch.arange(1,10,3)
x
torch.cat((x,x,x),0)


tensor([1, 4, 7, 1, 4, 7, 1, 4, 7])

First we create a tensor using arange function and then concatenate 3 times in rows

In [77]:
# Example 2 - working
new_data = torch.arange(1,24,2).reshape(-1,2)
new_data
torch.cat((new_data , torch.tensor([[1,2]])),0)

tensor([[ 1,  3],
        [ 5,  7],
        [ 9, 11],
        [13, 15],
        [17, 19],
        [21, 23],
        [ 1,  2]])

First we create a two dimensional arary and then concatenate them in rows

In [80]:
# Example 3 - breaking 
new_data
x
torch.cat((new_data,x))

RuntimeError: ignored

When concatating tensor should have same dimesion  , here when we tried to concat a tensor with (1,) dim with tensor with (2,) dim it thrown an error

 - Use this function when u want to make two tensor into one 

## Conclusion

So in this notebook we have covered five basic functions of tensors.
We have seen how we can create a tensor with zeros.
We have also created a identity matrix and covered the basics of tensor concatination. There are hundreds of useful tensor functions which we can use , for more information please go to offical python documentation.

## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for `torch.Tensor`: https://pytorch.org/docs/stable/tensors.html

In [0]:
!pip install jovian --upgrade --quiet

In [0]:
import jovian

In [0]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
